### ISSUE TITLE
Chameleon should use settings.xml if provided to the parent maven task

### ISSUE THREAD

**Issue by CSchulz** [arquillian/arquillian-container-chameleon#53] opened 2016-09-19 16:07 UTC
At the moment there is a complete new MavenWorkingSession for the chameleon runner, which ignores the settings.xml and makes trouble in corporate environments with proxy and/or mirror.

**Comment by bvarner** [comment] 2016-10-12 19:53
+1

This is going to keep me from being able to use this at the moment, which is a huge shame.

**Comment by bartoszmajsak** [comment] 2016-10-12 20:13
Thanks for reporting. Would anyone of you be interested in contributing this fix? You can count on my help any time.

**Comment by MatousJobanek** [comment] 2016-10-14 11:49
Hi,
if I understand it correctly - what you are saying is that chameleon [over here](https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/java/org/arquillian/container/chameleon/controller/Resolver.java#L43-L47) somehow ignores your ~/.m2/settings.xml file...?
Well, I've tried it locally and everything seem to be working without any problem... So, maybe I don't understand your problem correctly or I have completely different settings of my environment than you have. 
Could you please provide more information or just a simple reproducer?

**Comment by CSchulz** [comment] 2016-10-18 07:44
it seems to be more an issue with missing DNS resolution. But in general it would be nice if Chameleon does not encounter an issue if DNS for central.maven.org can't be resolved. I was expecting that it will ask directly at the mirror instead of resolving the DNS on its own.

**Comment by MatousJobanek** [comment] 2016-10-24 12:18
What I tried - I created my dummy repository containing all necessary bits, then I disconnected my PC from the internet, set path to the dummy repo as a remote repo (in my settings.xml) and tried a build of a chameleon test - everything passed.
This is a use case which is very hard to reproduce in different environment. If you know where the problem is and you know how to fix it, we will welcome any help/hints or PR.

**Comment by bvarner** [comment] 2016-10-25 18:15
No, I'm saying that I run maven with `mvn --settings ~/.m2/client_specific_settings.xml` where I customize things specific to corporate environments (say, when I'm on a client's VPN).

Just reading settings.xml is using my normal maven settings.xml, not the one I told maven to use which has the client's corporate nexus proxies (and any other profiles required to build) defined.

**Comment by MatousJobanek** [comment] 2016-10-26 11:47
@bvarner unfortunately, this feature is not supported by ShrinkWrap Resolver (using settings.xml specified on command line). Since the SW Resolver is internally used by Chameleon, it's not possible to use it here. 

You can try using SW Resolver maven plugin https://github.com/shrinkwrap/resolver#shrinkwrap-resolver-maven-plugin
Apart from using Maven plugin, there is probably no possible solution so far. If I think about it as a new feature that could be implemented, the only feasible way seems to be using arquillian.xml file and specifying it there.

Any other idea?

**Comment by bvarner** [comment] 2016-10-26 15:46
That's interesting, since we haven't had any other issue using shrinkwrap resolver during our integration tests that we _do_ have running with Arquillian without chameleon... (and we're resolving artifacts that only exist in the corporate proxy defined in my alternate settings.xml)

Hrmmm...

**Comment by MatousJobanek** [comment] 2016-11-01 08:46
@bvarner The only possible way I can think of (why other tests using resolver are working) is that you point to your settings.xml file using Resolver API:

`Maven.configureResolver().fromFile("your/alternate/settings.xml");`

or that you set the repository explicitly via the API:

`Maven.configureResolver().withRemoteRepo(repository);`

**Comment by bvarner** [comment] 2016-11-01 13:08
Looks like we're doing this (I'm not the source of this, so... I'm not sure why it was picked to do it this way)

`Maven.resolver().loadPomFromFile("pom.xml").importRuntimeDependencies().resolve().withTransitivity().asFile()`

**Comment by MatousJobanek** [comment] 2016-11-04 11:15
No idea then. Maybe some additional settings in the pom.xml file. Anyway, using settings.xml file defined on command line is not supported by Resolver.

Since your use case is completely valid, I implemented a new chameleon parameter `chameleonSettingsXml` which should enable you to use your arbitrary settings.xml file. Please, take a look at this PR: https://github.com/arquillian/arquillian-container-chameleon/pull/56

**Comment by McFoggy** [comment] 2016-11-09 16:03
could it be that you support default [shrinkwrap default system properties](https://github.com/shrinkwrap/resolver#system-properties) ?

a failsafe configuration could then look like:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <executions>
        <execution>
            <id>integration-test</id>
            <phase>integration-test</phase>
            <goals>
                <goal>integration-test</goal>
            </goals>
            <configuration>
                <systemPropertyVariables>
                    <org.apache.maven.global-settings>/d/dev/tools/apache/maven/latest/conf/settings.xml</org.apache.maven.global-settings>
                </systemPropertyVariables>
            </configuration>
        </execution>
        ...
    </executions>
</plugin>
```

the settings location file could also have been set via a property to externalize the location.
Perhaps also an already existing maven property exist for _global.settings_ location.

If not a simple plugin could bring it int the party but here we diverge ; might be that [ShrinkWrap Resolver Maven Plugin](https://github.com/shrinkwrap/resolver#shrinkwrap-resolver-maven-plugin) resolves exactly that.

**Comment by MatousJobanek** [comment] 2016-12-22 15:16
Hi, 
yeah, I didn't realized the possibility to hack it using the system properties from SWR. I have no idea why I was trying to solve it with additional properties in arq.xml, when there is already a solution implemented. I was probably too focused on the settings using `-s` parameter. Sorry for that.

Have you tried to use either `org.apache.maven.user-settings` or `org.apache.maven.global-settings` to solve your problem?

**Comment by McFoggy** [comment] 2016-12-22 15:33
> Have you tried to use either `org.apache.maven.user-settings` ...

@MatousJobanek if the question was addressed to me then I'd say no, cause sadly for the particular project I was on, I have moved away from chameleon.

**Closed** 2017-01-05 15:46 UTC

**Comment by bvarner** [comment] 2017-01-25 20:22
@MatousJobanek I was able to spend some time coming back to chameleon today, and yes. I can confirm the system property works!

It's not as elegant as I'd like, but it's functional. Thanks!

**Comment by CSchulz** [comment] 2017-04-11 07:57
It seems that there are still open issues with Beta1:

```
mvn -gs my-global-settings.xml failsafe:integration-test

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Apr 10, 2017 6:04:43 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNUNG: Failed downloading org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom from http://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.yaml:snakeyaml:pom:1.17 from/to central (http://repo1.maven.org/maven2): Error transferring file: repo1.maven.org from http://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom
Apr 10, 2017 6:04:43 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNUNG: Failed downloading org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar from http://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.yaml:snakeyaml:jar:1.17 from/to central (http://repo1.maven.org/maven2): Error transferring file: repo1.maven.org from http://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
```

Global settings:
```
    <mirror>
      <id>central</id>
      <mirrorOf>*</mirrorOf>
      <url>http://.../nexus/content/groups/public/</url>
    </mirror>
```

Interesting point besides, if I am using the user profile located settings.xml the system tries to load snakeyaml 1.15.

**Comment by CSchulz** [comment] 2017-04-11 08:04
It seems there is still an issue with Beta1:

```
mvn -Dorg.apache.maven.user-settings=my-global-settings.xml failsafe:integration-test

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Apr 10, 2017 6:04:43 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNUNG: Failed downloading org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom from http://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.yaml:snakeyaml:pom:1.17 from/to central (http://repo1.maven.org/maven2): Error transferring file: repo1.maven.org from http://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom
Apr 10, 2017 6:04:43 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNUNG: Failed downloading org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar from http://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.yaml:snakeyaml:jar:1.17 from/to central (http://repo1.maven.org/maven2): Error transferring file: repo1.maven.org from http://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
```

Global settings:
```
    <mirror>
      <id>central</id>
      <mirrorOf>*</mirrorOf>
      <url>http://.../nexus/content/groups/public/</url>
    </mirror>
```

Interesting point besides, if I am using the user profile located settings.xml the system tries to load snakeyaml 1.15.
